CREATE TABLE utente(
id_utente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nome VARCHAR(16),
cognome VARCHAR(16),
username VARCHAR(16),
password VARCHAR(8),
conto INTEGER,
venditore BOOLEAN);

CREATE TABLE album(
id_album INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nome_album VARCHAR(32),
coverLink VARCHAR(32),
tipo VARCHAR(8),
autore VARCHAR(32),
prezzo INTEGER,
id_vend INTEGER,
FOREIGN KEY (id_vend) REFERENCES utente(id_utente)
);

insert into utente(id_utente, nome, cognome, username, password, conto, venditore)
values (default,'Leonardo','Bonucci','lb19','0',300,true),
       (default,'Jamie','Vardy','jv9','0',300,true),
       (default,'Angelo','Pili','akp19','0',300,false);

insert into album(id_album, nome_album, coverLink, tipo, autore, prezzo, id_vend)
values (default,'Black Album','blackalbum.jpg','CD','Metallica',10,1),
       (default,'Mesmerize','soadm.jpg','CD','System of a down',10,1),
       (default,'Rosenrot','rosenrot.jpg','CD','Rammstein',10,1),
       (default,'Tra la via Emila e il West','viaem.jpg','Vinile','Guccini',10,2),
       (default,'Elettrico','elettrico.jpg','MP3','Rancore',10,2); 
